clear; clc; close all;
region = {...
    'lcerebellum','lthalamus','lthalamus_prop','lcaudate','lputamen',...
    'lpallidum', 'lhippo','lamygdala','laccumbens','lsubstnigra',...
    'rcerebellum','rthalamus','rthalamus_prop','rcaudate','rputamen',...
    'rpallidum',  'rhippo','ramygdala','raccumbens','rsubstnigra',...
    'brainstem'};%,...
    %'lcaudput','rcaudput','lbasgang','rbasgang',...
    %'brainstem','midbrain','pons','medulla','amygdala'};   
code = {...
    8,9,10,11,12,...
    13,17,18,26,27,...
    47, 48, 49, 50, 51,...
    52, 53, 54, 58, 59,...
    16};%, ...
    %136, 137, 169, 176,...
    %170, 173, 174, 175,218};
c = cell(1,length(code)); 

for i = 1:length(region)
    c{i}.region = region{i};
    c{i}.code = code{i};
end
reg_code = c; 
save('sregcode.mat','reg_code','region','code');



